name: kaisi_app
description: "A new Flutter project." 
publish_to: 'EL BAH Mohamed Amine ' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0' 
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  animations: ^2.0.0 
  lottie: ^3.1.0
  get: ^4.6.1 
  intl: ^0.19.0 
  iconsax: 0.0.8
  url_launcher: ^6.0.9
  connectivity_plus: ^6.0.3
  firebase_storage: ^11.7.4 
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  conditional_questions: '^2.0.0'
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  http: ^1.2.1  
  firebase_app_check: ^0.2.2+4  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_analytics: ^10.8.5
  google_sign_in: ^6.1.6
  flutter_bloc: ^7.1.0
  equatable: ^2.0.5
  # flutter_facebook_auth: ^6.0.2 

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^4.0.0 
flutter: 
  uses-material-design: true
  assets:
        - assets/images/   
        - assets/icons/ 
        - assets/SideBarImages/ 
        - assets/CoachImages/ 
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
